
name: Build MunichWays GeoJson

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm install
    - shell: bash
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: |
        echo "${SERVICE_ACCOUNT_JSON}" >> secret.json
        node create_geojson.mjs
    - uses: actions/upload-artifact@v4
      with:
        name: geojson
        path: munichways.geojson
